using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using PaymentService.Domain.Entities;
using PaymentService.Infrastructure.Persistence;

namespace PaymentService.API.Controllers;

[ApiController]
[Route("api/payment")]
public class PaymentController : ControllerBase
{
    private readonly PaymentDbContext _db;
    private readonly IConfiguration _config;

    public PaymentController(PaymentDbContext db, IConfiguration config)
    {
        _db = db;
        _config = config;
    }

    // GET api/payment/order/{orderId} — get payment status for an order
    [HttpGet("order/{orderId}")]
    public async Task<IActionResult> GetPaymentByOrder(Guid orderId)
    {
        var payment = await _db.Payments
            .FirstOrDefaultAsync(p => p.OrderId == orderId);

        if (payment == null)
            return NotFound(new { message = "Payment not found" });

        return Ok(new
        {
            payment.OrderId,
            payment.Amount,
            Status = payment.Status.ToString(),
            payment.PaymentMode,
            payment.CreatedAt,
            payment.ConfirmedAt
        });
    }

    // GET api/payment/saga/{orderId} — get saga state for an order
    [HttpGet("saga/{orderId}")]
    public async Task<IActionResult> GetSagaState(Guid orderId)
    {
        var saga = await _db.DispatchSagas
            .FirstOrDefaultAsync(s => s.OrderId == orderId);

        if (saga == null)
            return NotFound(new { message = "No saga found for this order" });

        return Ok(new
        {
            saga.OrderId,
            State = saga.State.ToString(),
            saga.PaymentLocked,
            saga.AgentAssigned,
            saga.StartedAt,
            saga.CompletedAt,
            saga.FailureReason
        });
    }

    [HttpPost("razorpay/create-order")]
    public IActionResult CreateRazorpayOrder([FromBody] CreateRazorpayOrderRequest req)
    {
        var keyId = _config["Razorpay:KeyId"];
        var keySecret = _config["Razorpay:KeySecret"];

        try
        {
            var client = new Razorpay.Api.RazorpayClient(keyId, keySecret);
            var options = new Dictionary<string, object>
            {
                { "amount", (int)(req.Amount * 100) }, // amount in the smallest currency unit (paise)
                { "currency", "INR" },
                { "receipt", req.OrderId.ToString("N") }
            };

            Razorpay.Api.Order order = client.Order.Create(options);
            string rzpOrderId = order["id"].ToString();

            return Ok(new { razorpayOrderId = rzpOrderId, amount = req.Amount, currency = "INR" });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new { success = false, message = "Failed to create Razorpay Order", error = ex.Message });
        }
    }

    [HttpPost("razorpay/verify")]
    public async Task<IActionResult> VerifyRazorpayPayment([FromBody] VerifyRazorpayRequest req)
    {
        var payment = await _db.Payments.FirstOrDefaultAsync(p => p.OrderId == req.OrderId);
        if (payment == null) return NotFound("Payment record not found");

        var keySecret = _config["Razorpay:KeySecret"];

        try
        {
            // Razorpay signature is generated by hashing (razorpay_order_id + "|" + razorpay_payment_id) with KeySecret
            string text = $"{req.RazorpayOrderId}|{req.RazorpayPaymentId}";
            var secretBytes = System.Text.Encoding.UTF8.GetBytes(keySecret ?? "");
            var textBytes = System.Text.Encoding.UTF8.GetBytes(text);

            using var hmac = new System.Security.Cryptography.HMACSHA256(secretBytes);
            byte[] hashBytes = hmac.ComputeHash(textBytes);
            string generatedSignature = BitConverter.ToString(hashBytes).Replace("-", "").ToLower();

            if (generatedSignature != req.RazorpaySignature.ToLower())
            {
                return BadRequest(new { success = false, message = "Invalid payment signature." });
            }
        }
        catch (Exception ex)
        {
            return BadRequest(new { success = false, message = "Error verifying payment signature.", error = ex.Message });
        }

        payment.ProviderOrderId = req.RazorpayOrderId;
        payment.ProviderPaymentId = req.RazorpayPaymentId;
        payment.Status = Domain.Enums.PaymentStatus.Confirmed;
        payment.ConfirmedAt = DateTime.UtcNow;

        _db.Payments.Update(payment);
        await _db.SaveChangesAsync();

        return Ok(new { success = true, message = "Payment verified successfully" });
    }
}

public class CreateRazorpayOrderRequest
{
    public decimal Amount { get; set; }
    public Guid OrderId { get; set; }
}

public class VerifyRazorpayRequest
{
    public Guid OrderId { get; set; }
    public string RazorpayOrderId { get; set; } = string.Empty;
    public string RazorpayPaymentId { get; set; } = string.Empty;
    public string RazorpaySignature { get; set; } = string.Empty;
}
